"""add_attachment_model

Revision ID: 4011e5381c8b
Revises: cbb05e26bf2b
Create Date: 2026-08-06 23:21:08.903587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4011e5381c8b'
down_revision: Union[str, None] = 'cbb05e26bf2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskflow_attachment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['taskflow_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskflow_attachment_id'), 'taskflow_attachment', ['id'], unique=False)
    op.create_index(op.f('ix_taskflow_attachment_task_id'), 'taskflow_attachment', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskflow_attachment_task_id'), table_name='taskflow_attachment')
    op.drop_index(op.f('ix_taskflow_attachment_id'), table_name='taskflow_attachment')
    op.drop_table('taskflow_attachment')
    # ### end Alembic commands ###
