"""Initial tables

Revision ID: a2f573325324
Revises: 
Create Date: 2026-07-08 02:48:53.540232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f573325324'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskflow_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskflow_user_email'), 'taskflow_user', ['email'], unique=True)
    op.create_index(op.f('ix_taskflow_user_id'), 'taskflow_user', ['id'], unique=False)
    op.create_table('taskflow_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'review', 'completed', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='taskpriority'), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['taskflow_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskflow_task_id'), 'taskflow_task', ['id'], unique=False)
    op.create_index(op.f('ix_taskflow_task_title'), 'taskflow_task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskflow_task_title'), table_name='taskflow_task')
    op.drop_index(op.f('ix_taskflow_task_id'), table_name='taskflow_task')
    op.drop_table('taskflow_task')
    op.drop_index(op.f('ix_taskflow_user_id'), table_name='taskflow_user')
    op.drop_index(op.f('ix_taskflow_user_email'), table_name='taskflow_user')
    op.drop_table('taskflow_user')
    # ### end Alembic commands ###
